import { createFileRoute } from "@tanstack/react-router";
import { DocsShell } from "@/components/docs/docs-shell";
import { GuideContent } from "@/components/docs/doc-content";
import { Button } from "@/components/ui/button";
import { getGuide } from "@/data/guides";
import logoAsset from "@/assets/rahapay-logo-on-dark.png.asset.json";
const guide=getGuide("introduction");
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Raha Pay API Documentation — KES Payments"},{name:"description",content:"Integrate KES collections, payouts, virtual accounts, balances and conversions with Raha Pay."},{property:"og:title",content:"Raha Pay API Documentation"},{property:"og:description",content:"Developer documentation for Raha Pay's Kenya payments API."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Index});
function Index(){if(!guide)return null;return <DocsShell currentPath="/" anchors={guide.sections.map(s=>({id:s.id,title:s.title}))}><section className="relative mb-12 overflow-hidden rounded-2xl bg-surface-night px-4 py-8 sm:px-8 lg:px-10"><div className="pointer-events-none absolute left-2 top-1/2 -translate-y-1/2 space-y-2 opacity-60" aria-hidden="true"><span className="block h-2 w-28 rounded-full bg-sky"/><span className="block h-2 w-40 rounded-full bg-violet"/><span className="block h-2 w-20 rounded-full bg-magenta"/><span className="block h-2 w-32 rounded-full bg-sky"/><span className="block h-2 w-16 rounded-full bg-violet"/></div><div className="relative grid min-w-0 grid-cols-[minmax(0,1fr)] items-center gap-8 md:grid-cols-[minmax(0,1.15fr)_minmax(260px,0.85fr)]"><img src={logoAsset.url} alt="Raha Pay — Move Money Your Way." className="block h-auto w-full min-w-0 object-contain object-left md:min-w-[360px]"/><div><p className="font-sans text-lg font-semibold text-code-foreground">Collect and pay out in KES through one API.</p><div className="mt-5 flex flex-wrap gap-3"><Button asChild><a href="{{DASHBOARD_URL}}">Get API keys</a></Button><Button asChild variant="outline" className="border-code-foreground/40 bg-transparent text-code-foreground hover:bg-code-foreground/10 hover:text-code-foreground"><a href="#quickstart">Read the quickstart</a></Button></div></div></div></section><GuideContent guide={guide}/></DocsShell>}
