import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, CreditCard, Radio, Send, ShieldCheck, Smartphone } from "lucide-react";
import { DocsShell } from "@/components/docs/docs-shell";
import { LanguageCodeTabs, requestExamples } from "@/components/docs/code-examples";
import { CodeBlock } from "@/components/docs/code-block";
import { Button } from "@/components/ui/button";
import { getEndpoint } from "@/data/endpoints";
import { docsConfig } from "@/data/config";
import logoAsset from "@/assets/rahapay-logo-on-dark.png.asset.json";

const endpoint=getEndpoint("create-mobile-payment");
const cards=[
 {title:"Accept payments",text:"Collect with M-Pesa, Airtel Money, bank transfer or hosted checkout.",slug:"payments-work",icon:CreditCard},
 {title:"Send money",text:"Pay mobile wallets and verified Kenyan bank accounts.",slug:"payouts-work",icon:Send},
 {title:"Listen for events",text:"Confirm final results through signed, retryable webhooks.",slug:"webhooks-overview",icon:Radio},
] as const;
const popular=[
 ["Quickstart","Create and confirm your first M-Pesa payment.","quickstart"],
 ["M-Pesa STK push","Build a direct customer approval flow.","mpesa-payment"],
 ["Hosted checkout","Redirect customers to a managed payment page.","hosted-checkout"],
 ["Bank payouts","Verify and pay a Kenyan bank account.","bank-payouts"],
 ["Verify webhooks","Authenticate an event before processing it.","verify-webhooks"],
 ["Errors","Map each code to a safe recovery action.","errors"],
] as const;

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Raha Pay API Documentation"},{name:"description",content:"Build M-Pesa, Airtel Money and Kenyan bank payments and payouts with Raha Pay."},{property:"og:title",content:"Raha Pay API Documentation"},{property:"og:description",content:"Developer documentation for payments, payouts and account events."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Index});

function Index(){return <DocsShell currentPath="/" anchors={[]} showPageFooter={false}><section className="relative overflow-hidden rounded-2xl bg-surface-night px-5 py-10 sm:px-8 lg:px-10"><div className="pointer-events-none absolute left-2 top-1/2 -translate-y-1/2 space-y-2 opacity-60" aria-hidden="true"><span className="block h-2 w-28 rounded-full bg-sky"/><span className="block h-2 w-40 rounded-full bg-violet"/><span className="block h-2 w-20 rounded-full bg-magenta"/><span className="block h-2 w-32 rounded-full bg-sky"/><span className="block h-2 w-16 rounded-full bg-violet"/></div><div className="relative grid items-center gap-8 md:grid-cols-[minmax(0,1.15fr)_minmax(260px,0.85fr)]"><img src={logoAsset.url} alt="Raha Pay — Move Money Your Way." className="block h-auto w-full object-contain object-left md:min-w-[360px]"/><div><p className="text-lg font-semibold text-code-foreground">Accept M-Pesa, Airtel Money and bank payments. Pay out in seconds.</p><div className="mt-5 flex flex-wrap gap-3"><Button asChild><a href={docsConfig.dashboardUrl}>Get API keys</a></Button><Button asChild variant="outline" className="border-code-foreground/40 bg-transparent text-code-foreground hover:bg-code-foreground/10 hover:text-code-foreground"><Link to="/guides/$slug" params={{slug:"quickstart"}}>Read the quickstart</Link></Button></div></div></div></section>
<section className="mt-12 grid gap-4 md:grid-cols-3">{cards.map(({title,text,slug,icon:Icon})=><Link key={title} to="/guides/$slug" params={{slug}} className="group rounded-[10px] border bg-surface-raised p-6 transition duration-200 hover:-translate-y-0.5 hover:border-primary"><span className="flex size-10 items-center justify-center rounded-md bg-violet-soft text-on-violet-soft"><Icon className="size-5"/></span><h2 className="mt-5 font-display text-xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Open guide <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></span></Link>)}</section>
<section className="mt-12"><div className="mb-6"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-ink-muted">Quickstart</p><h2 className="mt-2 font-display text-[28px] font-extrabold">Your first request</h2></div><div className="grid overflow-hidden rounded-[10px] border bg-surface-raised lg:grid-cols-[0.8fr_1.2fr]"><div className="p-6 lg:p-8"><ol className="space-y-7">{[["Get your Sandbox key","Create a secret key in the dashboard and keep it on your server."],["Send an STK push","Create a payment for 254712345678 using a unique order reference."],["Receive the webhook","Verify Raha-Signature, deduplicate the event and confirm the order."]].map(([title,text],index)=><li key={title} className="flex gap-4"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-violet-soft font-mono text-sm font-bold text-on-violet-soft">{index+1}</span><div><h3 className="font-display font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></li>)}</ol></div><div className="min-w-0 bg-code p-4 sm:p-6">{endpoint&&<LanguageCodeTabs examples={requestExamples(endpoint)}/>} {endpoint&&<div className="mt-5"><CodeBlock label="Response" code={JSON.stringify(endpoint.success,null,2)}/></div>}</div></div></section>
<section className="mt-12"><h2 className="font-display text-xl font-bold">Payment rails</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-[10px] border bg-surface-raised p-4"><div className="flex items-center gap-2 font-bold"><Smartphone className="size-4 text-primary"/>M-Pesa</div><p className="mt-2 text-sm text-muted-foreground">STK confirmation is usually available within 60 seconds.</p></div><div className="rounded-[10px] border bg-surface-raised p-4"><div className="flex items-center gap-2 font-bold"><Smartphone className="size-4 text-primary"/>Airtel Money</div><p className="mt-2 text-sm text-muted-foreground">Wallet confirmation is usually available within 60 seconds.</p></div><div className="rounded-[10px] border bg-surface-raised p-4"><div className="flex items-center gap-2 font-bold"><Building2 className="size-4 text-primary"/>Kenyan banks</div><p className="mt-2 text-sm text-muted-foreground">PesaLink is near real time; RTGS follows bank processing windows.</p></div></div></section>
<section className="mt-12"><h2 className="font-display text-xl font-bold">Popular guides</h2><div className="mt-5 grid gap-x-8 sm:grid-cols-2">{popular.map(([title,text,slug])=><Link key={slug} to="/guides/$slug" params={{slug}} className="group flex items-start justify-between gap-4 border-b py-5"><span><span className="font-display font-bold group-hover:text-primary">{title}</span><span className="mt-1 block text-sm text-muted-foreground">{text}</span></span><ArrowRight className="mt-1 size-4 shrink-0 text-primary"/></Link>)}</div></section>
<section className="mt-12 flex flex-col gap-5 rounded-[10px] border border-violet/20 bg-violet-soft p-6 text-on-violet-soft sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><ShieldCheck className="mt-1 size-5 shrink-0"/><div><h2 className="font-display text-xl font-bold">Everything works in Sandbox first.</h2><p className="mt-1">Test numbers, forced failures and instant top-ups.</p></div></div><Button asChild variant="outline" className="border-violet text-on-violet-soft"><Link to="/guides/$slug" params={{slug:"sandbox-testing"}}>Sandbox testing <ArrowRight/></Link></Button></section>
<footer className="mt-12 flex flex-col gap-4 border-t py-8 text-sm text-muted-foreground sm:flex-row sm:items-center"><div className="flex flex-wrap gap-x-5 gap-y-2"><a href={`mailto:${docsConfig.supportEmail}`} className="hover:text-primary">Support email</a><a href={docsConfig.statusUrl} className="hover:text-primary">Status page</a><Link to="/guides/$slug" params={{slug:"changelog"}} className="hover:text-primary">Changelog</Link></div><span className="sm:ml-auto">© 2026 Raha Pay Limited</span></footer></DocsShell>}
