import { useMemo, useState } from "react";
import { useLocation } from "@tanstack/react-router";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";
import { Bot, Sparkles, ThumbsDown, ThumbsUp } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Conversation, ConversationContent, ConversationEmptyState, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageActions, MessageAction, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputBody, PromptInputFooter, PromptInputSubmit, PromptInputTextarea } from "@/components/ai-elements/prompt-input";
import { Shimmer } from "@/components/ai-elements/shimmer";
import { useAssistant } from "./assistant-context";
import markAsset from "@/assets/rahapay-mark-exact.png.asset.json";

function visitorId(){if(typeof window==="undefined")return "server";let id=localStorage.getItem("rahapay-assistant-visitor");if(!id){id=crypto.randomUUID();localStorage.setItem("rahapay-assistant-visitor",id)}return id}
export function AssistantPanel(){const {open,setOpen,pageContext,snippet}=useAssistant();const pathname=useLocation({select:(l)=>l.pathname});const [rated,setRated]=useState<Record<string,string>>({});const transport=useMemo(()=>new DefaultChatTransport({api:"/api/chat",headers:{"X-Visitor-Id":visitorId()},prepareSendMessagesRequest:({messages,id})=>({body:{id,messages,pageContext:pageContext||pathname,snippet}})}),[pageContext,pathname,snippet]);const {messages,sendMessage,status,error,stop}=useChat({id:"rahapay-session",transport});
const submit=({text}:{text:string})=>{if(text.trim())void sendMessage({text:text.trim()})};
const rate=async(id:string,rating:"up"|"down")=>{setRated(v=>({...v,[id]:rating}));await fetch("/api/assistant-feedback",{method:"POST",headers:{"content-type":"application/json","X-Visitor-Id":visitorId()},body:JSON.stringify({messageId:id,rating})})};
return <Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="flex h-full w-full flex-col gap-0 p-0 sm:max-w-[440px]"><SheetHeader className="border-b px-5 py-4 pr-14 text-left"><div className="flex items-center gap-3"><img src={markAsset.url} alt="" className="h-7 w-auto"/><div><SheetTitle className="font-display">Raha Pay Assistant</SheetTitle><SheetDescription className="text-xs">Grounded in this documentation</SheetDescription></div></div></SheetHeader><Conversation className="min-h-0"><ConversationContent className="gap-5 px-5 py-6">{messages.length===0&&<ConversationEmptyState icon={<Sparkles className="size-8 text-primary"/>} title="How can I help?" description="Ask about payments, payouts, Virtual accounts, events or API requests."><div className="mt-4 grid gap-2 text-left">{["How do I test an M-Pesa payment?","What KYC is needed for a Virtual account?","Explain webhook verification."].map(q=><Button key={q} variant="outline" className="h-auto justify-start whitespace-normal py-2 text-left" onClick={()=>void sendMessage({text:q})}>{q}</Button>)}</div></ConversationEmptyState>}{messages.map((message)=><Message from={message.role} key={message.id}><MessageContent>{message.parts.map((part,index)=>part.type==="text"?<MessageResponse key={index}>{part.text}</MessageResponse>:null)}</MessageContent>{message.role==="assistant"&&status!=="streaming"&&<MessageActions><MessageAction tooltip="Helpful" onClick={()=>void rate(message.id,"up")} variant={rated[message.id]==="up"?"secondary":"ghost"}><ThumbsUp/></MessageAction><MessageAction tooltip="Not helpful" onClick={()=>void rate(message.id,"down")} variant={rated[message.id]==="down"?"secondary":"ghost"}><ThumbsDown/></MessageAction></MessageActions>}</Message>)}{status==="submitted"&&<Shimmer className="text-sm">Looking through the Raha Pay docs…</Shimmer>}{error&&<div className="rounded-lg border border-danger/30 bg-danger-ground p-3 text-sm text-danger">{error.message.includes("429")?"You have reached 20 questions this hour. Try again later.":"The assistant could not answer right now. Please try again."}</div>}</ConversationContent><ConversationScrollButton/></Conversation><div className="border-t bg-surface-raised p-4"><PromptInput onSubmit={submit} className="rounded-[10px]"><PromptInputBody><PromptInputTextarea placeholder="Ask the Raha Pay docs…"/></PromptInputBody><PromptInputFooter><span className="px-2 text-[11px] text-muted-foreground">Do not paste secret keys.</span><PromptInputSubmit status={status} onStop={stop}/></PromptInputFooter></PromptInput><p className="mt-2 text-center text-[10px] text-muted-foreground">Answers can be wrong. Verify important details in the cited pages.</p></div></SheetContent></Sheet>}
