import { AlertTriangle, Check, Clipboard, Hash, Info, Lightbulb } from "lucide-react";
import { useState } from "react";
import type { Guide, GuideSection } from "@/data/guides";
import { Button } from "@/components/ui/button";
import { CodeBlock } from "./code-block";
import { SequenceDiagram } from "./sequence-diagram";
import { cn } from "@/lib/utils";

function Heading({ id, children }: { id:string; children:string }) {
 const [copied,setCopied]=useState(false); const copy=async()=>{const url=`${window.location.origin}${window.location.pathname}#${id}`;await navigator.clipboard.writeText(url);window.history.replaceState(null,"",`#${id}`);setCopied(true);window.setTimeout(()=>setCopied(false),1200)};
 return <h2 id={id} className="group scroll-mt-24 pt-4 font-display text-xl font-bold"><Button variant="ghost" size="icon" onClick={copy} className="-ml-10 mr-1 inline-flex size-8 align-middle opacity-0 group-hover:opacity-100 focus:opacity-100" aria-label={`Copy link to ${children}`}>{copied?<Check/>:<Hash/>}</Button>{children}</h2>;
}
function RichText({ children }: { children:string }) { const parts=children.split(/(`[^`]+`)/g); return <>{parts.map((part,i)=>part.startsWith("`")&&part.endsWith("`")?<code key={i} className="rounded bg-muted px-1.5 py-0.5 font-mono text-[0.9em] text-primary">{part.slice(1,-1)}</code>:part)}</> }
function Callout({ value }: { value: NonNullable<GuideSection["callout"]> }) { const Icon=value.kind==="warning"?AlertTriangle:value.kind==="tip"?Lightbulb:Info; const label=value.kind==="warning"?"Warning":value.kind==="tip"?"Tip":"Note"; return <div className={cn("my-5 rounded-[10px] border p-4",value.kind==="warning"?"border-warning/30 bg-warning-ground text-warning":value.kind==="tip"?"border-violet/20 bg-violet-soft text-on-violet-soft":"border-info/30 bg-info-ground text-info")}><div className="flex gap-3"><Icon className="mt-0.5 size-4 shrink-0"/><div><p className="text-sm font-bold">{label}{value.title&&value.title!==label?`: ${value.title}`:""}</p><p className="mt-1 text-sm leading-6"><RichText>{value.text}</RichText></p></div></div></div> }
function DataTable({ table }: { table:NonNullable<GuideSection["table"]> }) { return <div className="my-5 overflow-x-auto rounded-md border"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr>{table.headers.map(h=><th key={h} className="border-b px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{table.rows.map((row,i)=><tr key={i} className="border-b last:border-0">{row.map((cell,j)=><td key={j} className={cn("px-4 py-3 align-top",j===0&&"font-medium text-foreground",j>0&&"text-muted-foreground")}>{cell}</td>)}</tr>)}</tbody></table></div> }
export function GuideContent({ guide }: { guide:Guide }) { return <><div className="mb-12"><p className="mb-3 text-xs font-extrabold uppercase tracking-[0.18em] text-ink-muted">{guide.group}</p><h1 className="font-display text-[28px] font-extrabold leading-9">{guide.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">{guide.description}</p></div><div className="space-y-10">{guide.sections.map(section=><section key={section.id}><Heading id={section.id}>{section.title}</Heading>{section.paragraphs?.map((p,i)=><p key={i} className="mt-4 leading-7 text-content"><RichText>{p}</RichText></p>)}{section.bullets&&<ul className="mt-4 space-y-2 pl-1">{section.bullets.map(item=><li key={item} className="flex gap-3 leading-7 text-content"><span className="mt-3 size-1.5 shrink-0 rounded-full bg-primary"/><span><RichText>{item}</RichText></span></li>)}</ul>}{section.callout&&<Callout value={section.callout}/>} {section.table&&<DataTable table={section.table}/>} {section.code&&<CodeBlock code={section.code}/>} {section.diagram&&<SequenceDiagram type={section.diagram}/>}</section>)}</div></> }
