import { Link, useLocation, useNavigate } from "@tanstack/react-router";
import { BookOpen, Bot, Check, ChevronLeft, ChevronRight, Code2, CreditCard, ExternalLink, Landmark, Menu, Moon, Radio, Search, Send, Sun, ThumbsDown, ThumbsUp } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { guides, guideGroups } from "@/data/guides";
import { docsConfig } from "@/data/config";
import { endpointGroups, endpoints } from "@/data/endpoints";
import { useDocs } from "./docs-context";
import { useAssistant } from "./assistant-context";
import { cn } from "@/lib/utils";
import markAsset from "@/assets/rahapay-mark-exact.png.asset.json";

const sectionIcons={"Start here":BookOpen,"Accept payments":CreditCard,"Virtual accounts":Landmark,"Send money":Send,Account:Landmark,Events:Radio,Reference:BookOpen};

function Navigation({ close }: { close?: () => void }) {
  const pathname=useLocation({select:(location)=>location.pathname});
  return <nav className="space-y-7 pb-8" aria-label="Documentation navigation">
    {guideGroups.map(group=>{const Icon=sectionIcons[group as keyof typeof sectionIcons]??BookOpen;return <div key={group}><p className="mb-2 flex items-center gap-2 px-3 text-xs font-extrabold uppercase tracking-[0.18em] text-nav-label"><Icon className="size-3.5"/>{group}</p><ul className="space-y-0.5">{guides.filter(g=>g.group===group).map(item=>{const to=item.slug==="introduction"?"/":`/guides/${item.slug}`; const active=pathname===to; const classes=cn("block rounded-md border-l-2 px-3 py-1.5 text-[13px] transition-colors",active?"border-primary bg-nav-active font-medium text-foreground":"border-transparent text-muted-foreground hover:bg-accent hover:text-foreground"); return <li key={item.slug}>{item.slug==="introduction"?<Link to="/" onClick={close} className={classes}>{item.title}</Link>:<Link to="/guides/$slug" params={{slug:item.slug}} onClick={close} className={classes}>{item.title}</Link>}</li>})}</ul></div>})}
    <div><p className="mb-2 flex items-center gap-2 px-3 text-xs font-extrabold uppercase tracking-[0.18em] text-nav-label"><Code2 className="size-3.5"/>API reference</p>{endpointGroups.map(group=><div key={group} className="mb-4"><p className="px-3 py-1 text-xs font-semibold text-foreground">{group}</p><ul>{endpoints.filter(e=>e.group===group).map(item=><li key={item.slug}><Link to="/api-reference/$slug" params={{slug:item.slug}} onClick={close} className={cn("flex items-center gap-2 rounded-md px-3 py-1.5 text-[13px] text-muted-foreground hover:bg-accent hover:text-foreground",pathname===`/api-reference/${item.slug}`&&"bg-nav-active font-medium text-foreground")}><span className={cn("w-8 font-mono text-[10px] font-bold",item.method==="GET"?"text-info":"text-success")}>{item.method}</span><span className="truncate">{item.title}</span></Link></li>)}</ul></div>)}</div>
  </nav>;
}

function SearchDialog({ open, setOpen }: { open:boolean; setOpen:(open:boolean)=>void }) {
 const [query,setQuery]=useState(""); const navigate=useNavigate();
 const results=useMemo(()=>{const q=query.toLowerCase().trim(); const items=[...guides.map(item=>({title:item.title,description:item.description,group:item.group,to:item.slug==="introduction"?"/":`/guides/${item.slug}`})),...endpoints.map(item=>({title:item.title,description:`${item.method} ${item.path}`,group:item.group,to:`/api-reference/${item.slug}`}))]; return q?items.filter(item=>`${item.title} ${item.description} ${item.group}`.toLowerCase().includes(q)).slice(0,12):items.slice(0,8)},[query]);
 const select=(to:string)=>{setOpen(false);setQuery("");void navigate({to})};
 return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="top-[18%] max-w-2xl translate-y-0 gap-0 overflow-hidden p-0"><DialogTitle className="sr-only">Search documentation</DialogTitle><div className="flex items-center border-b px-4"><Search className="size-4 text-muted-foreground"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search guides and endpoints…" className="h-14 w-full bg-transparent px-3 text-sm outline-none placeholder:text-muted-foreground"/><kbd className="rounded border bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">ESC</kbd></div><div className="max-h-[430px] overflow-y-auto p-2">{results.length?results.map(item=><button key={item.to} onClick={()=>select(item.to)} className="flex w-full items-start gap-3 rounded-md px-3 py-3 text-left hover:bg-accent"><BookOpen className="mt-0.5 size-4 text-primary"/><span className="min-w-0"><span className="block text-sm font-medium">{item.title}</span><span className="mt-0.5 block truncate text-xs text-muted-foreground">{item.group} · {item.description}</span></span></button>):<p className="p-8 text-center text-sm text-muted-foreground">No documentation found.</p>}</div></DialogContent></Dialog>;
}

function TopBar() {
 const {environment,setEnvironment,theme,toggleTheme}=useDocs(); const {openAssistant}=useAssistant(); const pathname=useLocation({select:(location)=>location.pathname}); const [searchOpen,setSearchOpen]=useState(false);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[]);
  const tabClass="flex h-full items-center border-b-2 border-transparent px-3 text-sm font-medium text-muted-foreground hover:text-foreground";
  return <><header className="fixed inset-x-0 top-0 z-40 h-16 border-b bg-surface-raised"><div className="flex h-full items-center gap-3 px-4 lg:px-6"><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open navigation"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-[310px] overflow-y-auto p-4"><SheetTitle className="mb-5 font-display text-xl">Raha Pay</SheetTitle><Navigation/></SheetContent></Sheet><Link to="/" className="mr-2 flex items-center gap-2 font-display text-[18px] font-extrabold text-ink"><img src={markAsset.url} alt="" className="h-7 w-auto shrink-0 object-contain"/>Raha Pay<span className="rounded-md border px-1.5 py-0.5 font-sans text-[11px] font-bold text-muted-foreground">Docs</span></Link><div className="hidden h-full items-center gap-1 md:flex"><Link to="/" activeOptions={{exact:true}} activeProps={{className:"text-foreground border-primary"}} className={tabClass}>Guides</Link><Link to="/api-reference" activeProps={{className:"text-foreground border-primary"}} className={tabClass}>API Reference</Link><Link to="/guides/$slug" params={{slug:"changelog"}} activeProps={{className:"text-foreground border-primary"}} className={tabClass}>Changelog</Link></div><div className="ml-auto flex items-center gap-2"><Button variant="outline" onClick={()=>openAssistant(pathname)} className="hidden h-9 lg:inline-flex"><Bot/>Ask AI</Button><Button variant="outline" onClick={()=>setSearchOpen(true)} className="hidden h-[38px] w-[300px] justify-start text-muted-foreground lg:flex"><Search/><span>Search docs</span><kbd className="ml-auto text-[10px]">⌘K</kbd></Button><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setSearchOpen(true)} aria-label="Search"><Search/></Button><div className="hidden rounded-md border bg-muted p-0.5 sm:flex" aria-label="Environment"><Button variant="ghost" size="sm" onClick={()=>setEnvironment("sandbox")} className={cn("h-7 px-2.5 text-xs",environment==="sandbox"?"bg-background text-foreground":"text-muted-foreground")}>Sandbox</Button><Button variant="ghost" size="sm" onClick={()=>setEnvironment("live")} className={cn("h-7 px-2.5 text-xs",environment==="live"?"bg-background text-foreground":"text-muted-foreground")}>{environment==="live"&&<span className="size-1.5 rounded-full bg-magenta"/>}Live</Button></div><Button variant="ghost" size="icon" onClick={toggleTheme} aria-label="Toggle color theme">{theme==="light"?<Moon/>:<Sun/>}</Button><Button asChild className="hidden sm:inline-flex"><a href={docsConfig.dashboardUrl}>Dashboard<ExternalLink/></a></Button></div></div></header><SearchDialog open={searchOpen} setOpen={setSearchOpen}/></>;
}

export function DocsShell({ children, anchors=[], currentPath, api=false, rightRail, showPageFooter=true }: { children:ReactNode; anchors?:{id:string;title:string}[]; currentPath:string; api?:boolean; rightRail?:ReactNode; showPageFooter?:boolean }) {
 const all=api?endpoints.map(e=>({title:e.title,slug:e.slug,kind:"api" as const,path:`/api-reference/${e.slug}`})):guides.map(g=>({title:g.title,slug:g.slug,kind:"guide" as const,path:g.slug==="introduction"?"/":`/guides/${g.slug}`})); const index=all.findIndex(i=>i.path===currentPath); const previous=index>0?all[index-1]:undefined; const next=index>=0&&index<all.length-1?all[index+1]:undefined; const [helpful,setHelpful]=useState<boolean|null>(null);
 const navLink=(item:typeof previous,direction:"previous"|"next")=>{if(!item)return <span/>; const body=<><span className={cn("flex items-center gap-1 text-xs text-muted-foreground",direction==="next"&&"justify-end")}>{direction==="previous"&&<ChevronLeft className="size-3"/>}{direction==="previous"?"Previous":"Next"}{direction==="next"&&<ChevronRight className="size-3"/>}</span><span className="mt-1 block text-sm font-semibold group-hover:text-primary">{item.title}</span></>; const classes=cn("group rounded-md border p-4 hover:border-primary",direction==="next"&&"text-right"); if(item.kind==="api")return <Link to="/api-reference/$slug" params={{slug:item.slug}} className={classes}>{body}</Link>; if(item.slug==="introduction")return <Link to="/" className={classes}>{body}</Link>; return <Link to="/guides/$slug" params={{slug:item.slug}} className={classes}>{body}</Link>};
 return <div className="min-h-screen bg-background"><TopBar/><aside className="fixed bottom-0 left-0 top-16 hidden w-[272px] overflow-y-auto border-r px-4 pt-7 lg:block"><Navigation/></aside><main className="pt-16 lg:pl-[272px]"><div className={cn("mx-auto grid max-w-[1480px]",api?"xl:grid-cols-[minmax(0,1fr)_520px]":"grid-cols-1")}><article className="min-w-0 px-5 py-10 sm:px-8 lg:px-12 lg:py-14">{children}{showPageFooter&&<footer className="mt-16 border-t pt-8"><div className="mb-8 flex items-center justify-center gap-3 text-sm"><span className="text-muted-foreground">Was this page helpful?</span>{helpful===null?<><Button variant="outline" size="icon" onClick={()=>setHelpful(true)} aria-label="Yes, helpful"><ThumbsUp/></Button><Button variant="outline" size="icon" onClick={()=>setHelpful(false)} aria-label="No, not helpful"><ThumbsDown/></Button></>:<span className="inline-flex items-center gap-2 text-primary"><Check className="size-4"/>Thanks for the feedback.</span>}</div><div className="grid grid-cols-2 gap-3">{navLink(previous,"previous")}{navLink(next,"next")}</div><p className="mt-8 text-center text-xs text-ink-muted">© 2026 Raha Pay Limited</p></footer>}</article>{api&&<aside className="sticky top-16 hidden h-[calc(100vh-4rem)] overflow-y-auto border-l px-6 py-14 xl:block">{rightRail ?? <div className="flex items-center gap-2 text-xs font-semibold uppercase text-nav-label"><Code2 className="size-4"/>Code examples</div>}</aside>}</div></main></div>;
}
