import { Link, useLocation, useNavigate } from "@tanstack/react-router";
import { BookOpen, Check, ChevronLeft, ChevronRight, Code2, ExternalLink, Menu, Moon, Search, Sun, ThumbsDown, ThumbsUp, X } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { guides, guideGroups } from "@/data/guides";
import { endpointGroups, endpoints } from "@/data/endpoints";
import { useDocs } from "./docs-context";
import { cn } from "@/lib/utils";

const tabs = [{label:"Guides",to:"/"},{label:"API Reference",to:"/api-reference"},{label:"Changelog",to:"/guides/$slug",params:{slug:"changelog"}}] as const;

function Navigation({ close }: { close?: () => void }) {
  const pathname=useLocation({select:(location)=>location.pathname});
  return <nav className="space-y-7 pb-8" aria-label="Documentation navigation">
    {guideGroups.map(group=><div key={group}><p className="mb-2 px-3 text-[11px] font-bold uppercase text-nav-label">{group}</p><ul className="space-y-0.5">{guides.filter(g=>g.group===group).map(item=>{const to=item.slug==="introduction"?"/":`/guides/${item.slug}`; const active=pathname===to; return <li key={item.slug}><Link to={item.slug==="introduction"?"/":"/guides/$slug"} params={item.slug==="introduction"?undefined:{slug:item.slug}} onClick={close} className={cn("block rounded-md border-l-2 px-3 py-1.5 text-[13px] transition-colors",active?"border-primary bg-nav-active font-medium text-foreground":"border-transparent text-muted-foreground hover:bg-accent hover:text-foreground")}>{item.title}</Link></li>})}</ul></div>)}
    <div><p className="mb-2 px-3 text-[11px] font-bold uppercase text-nav-label">API Reference</p>{endpointGroups.map(group=><div key={group} className="mb-4"><p className="px-3 py-1 text-xs font-semibold text-foreground">{group}</p><ul>{endpoints.filter(e=>e.group===group).map(item=><li key={item.slug}><Link to="/api-reference/$slug" params={{slug:item.slug}} onClick={close} className={cn("flex items-center gap-2 rounded-md px-3 py-1.5 text-[13px] text-muted-foreground hover:bg-accent hover:text-foreground",pathname===`/api-reference/${item.slug}`&&"bg-nav-active font-medium text-foreground")}><span className={cn("w-8 font-mono text-[10px] font-bold",item.method==="GET"?"text-method-get":"text-method-post")}>{item.method}</span><span className="truncate">{item.title}</span></Link></li>)}</ul></div>)}</div>
  </nav>;
}

function SearchDialog({ open, setOpen }: { open:boolean; setOpen:(open:boolean)=>void }) {
 const [query,setQuery]=useState(""); const navigate=useNavigate();
 const results=useMemo(()=>{const q=query.toLowerCase().trim(); const items=[...guides.map(item=>({title:item.title,description:item.description,group:item.group,to:item.slug==="introduction"?"/":`/guides/${item.slug}`})),...endpoints.map(item=>({title:item.title,description:`${item.method} ${item.path}`,group:item.group,to:`/api-reference/${item.slug}`}))]; return q?items.filter(item=>`${item.title} ${item.description} ${item.group}`.toLowerCase().includes(q)).slice(0,12):items.slice(0,8)},[query]);
 const select=(to:string)=>{setOpen(false);setQuery("");void navigate({to})};
 return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="top-[18%] max-w-2xl translate-y-0 gap-0 overflow-hidden p-0"><DialogTitle className="sr-only">Search documentation</DialogTitle><div className="flex items-center border-b px-4"><Search className="size-4 text-muted-foreground"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search guides and endpoints…" className="h-14 w-full bg-transparent px-3 text-sm outline-none placeholder:text-muted-foreground"/><kbd className="rounded border bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">ESC</kbd></div><div className="max-h-[430px] overflow-y-auto p-2">{results.length?results.map(item=><button key={item.to} onClick={()=>select(item.to)} className="flex w-full items-start gap-3 rounded-md px-3 py-3 text-left hover:bg-accent"><BookOpen className="mt-0.5 size-4 text-primary"/><span className="min-w-0"><span className="block text-sm font-medium">{item.title}</span><span className="mt-0.5 block truncate text-xs text-muted-foreground">{item.group} · {item.description}</span></span></button>):<p className="p-8 text-center text-sm text-muted-foreground">No documentation found.</p>}</div></DialogContent></Dialog>;
}

function TopBar() {
 const {environment,setEnvironment,theme,toggleTheme}=useDocs(); const [searchOpen,setSearchOpen]=useState(false);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setSearchOpen(true)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[]);
 return <><header className="fixed inset-x-0 top-0 z-40 h-16 border-b bg-background/95 backdrop-blur"><div className="flex h-full items-center gap-3 px-4 lg:px-6"><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open navigation"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-[310px] overflow-y-auto p-4"><SheetTitle className="mb-5 font-display text-xl">Rahapay</SheetTitle><Navigation/></SheetContent></Sheet><Link to="/" className="mr-2 flex items-center gap-2 font-display text-xl font-bold"><span className="grid size-7 place-items-center rounded-md bg-primary text-sm text-primary-foreground">R</span>Rahapay</Link><div className="hidden h-full items-center gap-1 md:flex">{tabs.map(tab=><Link key={tab.label} to={tab.to} params={"params" in tab?tab.params:undefined} activeOptions={{exact:tab.to==="/"}} activeProps={{className:"text-foreground border-primary"}} className="flex h-full items-center border-b-2 border-transparent px-3 text-sm font-medium text-muted-foreground hover:text-foreground">{tab.label}</Link>)}</div><div className="ml-auto flex items-center gap-2"><Button variant="outline" onClick={()=>setSearchOpen(true)} className="hidden h-9 w-56 justify-start text-muted-foreground lg:flex"><Search/><span>Search docs</span><kbd className="ml-auto text-[10px]">⌘K</kbd></Button><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setSearchOpen(true)} aria-label="Search"><Search/></Button><div className="hidden rounded-md border bg-muted p-0.5 sm:flex" aria-label="Environment"><button onClick={()=>setEnvironment("sandbox")} className={cn("h-7 rounded px-2.5 text-xs font-medium",environment==="sandbox"?"bg-background text-foreground shadow-sm":"text-muted-foreground")}>Sandbox</button><button onClick={()=>setEnvironment("live")} className={cn("h-7 rounded px-2.5 text-xs font-medium",environment==="live"?"bg-background text-foreground shadow-sm":"text-muted-foreground")}>Live</button></div><Button variant="ghost" size="icon" onClick={toggleTheme} aria-label="Toggle color theme">{theme==="light"?<Moon/>:<Sun/>}</Button><Button asChild className="hidden sm:inline-flex"><a href="{{DASHBOARD_URL}}">Dashboard<ExternalLink/></a></Button></div></div></header><SearchDialog open={searchOpen} setOpen={setSearchOpen}/></>;
}

export function DocsShell({ children, anchors=[], currentPath, api=false }: { children:ReactNode; anchors?:{id:string;title:string}[]; currentPath:string; api?:boolean }) {
 const all=api?endpoints.map(e=>({title:e.title,path:`/api-reference/${e.slug}`})):guides.map(g=>({title:g.title,path:g.slug==="introduction"?"/":`/guides/${g.slug}`})); const index=all.findIndex(i=>i.path===currentPath); const [helpful,setHelpful]=useState<boolean|null>(null);
 return <div className="min-h-screen bg-background"><TopBar/><aside className="fixed bottom-0 left-0 top-16 hidden w-64 overflow-y-auto border-r px-4 pt-7 lg:block"><Navigation/></aside><main className="pt-16 lg:pl-64"><div className={cn("mx-auto grid max-w-[1480px]",api?"xl:grid-cols-[minmax(0,1fr)_430px]":"xl:grid-cols-[minmax(0,820px)_220px]")}><article className="min-w-0 px-5 py-10 sm:px-8 lg:px-12 lg:py-14">{children}<footer className="mt-16 border-t pt-8"><div className="mb-8 flex items-center justify-center gap-3 text-sm"><span className="text-muted-foreground">Was this page helpful?</span>{helpful===null?<><Button variant="outline" size="icon" onClick={()=>setHelpful(true)} aria-label="Yes, helpful"><ThumbsUp/></Button><Button variant="outline" size="icon" onClick={()=>setHelpful(false)} aria-label="No, not helpful"><ThumbsDown/></Button></>:<span className="inline-flex items-center gap-2 text-primary"><Check className="size-4"/>Thanks for the feedback.</span>}</div><div className="grid grid-cols-2 gap-3">{index>0?<Link to={all[index-1].path} className="group rounded-md border p-4 hover:border-primary"><span className="flex items-center gap-1 text-xs text-muted-foreground"><ChevronLeft className="size-3"/>Previous</span><span className="mt-1 block text-sm font-semibold group-hover:text-primary">{all[index-1].title}</span></Link>:<span/>}{index>=0&&index<all.length-1?<Link to={all[index+1].path} className="group rounded-md border p-4 text-right hover:border-primary"><span className="flex items-center justify-end gap-1 text-xs text-muted-foreground">Next<ChevronRight className="size-3"/></span><span className="mt-1 block text-sm font-semibold group-hover:text-primary">{all[index+1].title}</span></Link>:null}</div></footer></article><aside className="sticky top-16 hidden h-[calc(100vh-4rem)] overflow-y-auto border-l px-6 py-14 xl:block">{api?<div className="flex items-center gap-2 text-xs font-semibold uppercase text-nav-label"><Code2 className="size-4"/>Code examples</div>:<><p className="mb-4 text-xs font-semibold uppercase text-nav-label">On this page</p><nav className="space-y-2">{anchors.map(a=><a key={a.id} href={`#${a.id}`} className="block text-[13px] leading-5 text-muted-foreground hover:text-primary">{a.title}</a>)}</nav></>}</aside></div></main></div>;
}
