import { Check, Hash } from "lucide-react";
import { useState } from "react";
import type { ApiEndpoint } from "@/data/endpoints";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CodeBlock } from "./code-block";
import { cn } from "@/lib/utils";

function requestCode(endpoint:ApiEndpoint,language:string){ const body=endpoint.request?JSON.stringify(endpoint.request,null,2):""; const url=`{{BASE_URL}}${endpoint.path.replace("{payment_id}","rp_pay_8Kq2Xw91").replace("{payout_id}","rp_po_3Vn7Lm20").replace("{transaction_id}","rp_pay_8Kq2Xw91")}`; const idempotency=endpoint.method==="POST"?` \
  -H "Idempotency-Key: request-10492"`:""; if(language==="curl")return `curl -X ${endpoint.method} "${url}" \\\n  -H "{{AUTH_HEADER}}: {{SECRET_KEY_PREFIX}}test_example" \\\n  -H "Content-Type: application/json"${idempotency}${body?` \\\n  -d '${body}'`:""}`; if(language==="node")return `const response = await fetch("${url}", {\n  method: "${endpoint.method}",\n  headers: {\n    "{{AUTH_HEADER}}": "{{SECRET_KEY_PREFIX}}test_example",\n    "Content-Type": "application/json"\n  }${body?`,\n  body: JSON.stringify(${body})`:""}\n});\nconst result = await response.json();`; if(language==="python")return `response = requests.${endpoint.method.toLowerCase()}(\n    "${url}",\n    headers={"{{AUTH_HEADER}}": "{{SECRET_KEY_PREFIX}}test_example"}${body?`,\n    json=${body.replaceAll("true","True").replaceAll("false","False")}`:""}\n)\nresult = response.json()`; return `$response = $client->request('${endpoint.method}', '${url}', [\n  'headers' => ['{{AUTH_HEADER}}' => '{{SECRET_KEY_PREFIX}}test_example']${body?`,\n  'json' => ${body}`:""}\n]);` }
function AnchorHeading({id,children}:{id:string;children:string}){const[copied,setCopied]=useState(false);return <h2 id={id} className="group scroll-mt-24 pt-5 font-display text-xl font-bold"><Button variant="ghost" size="icon" className="-ml-10 mr-1 inline-flex size-8 align-middle opacity-0 group-hover:opacity-100" onClick={async()=>{await navigator.clipboard.writeText(`${location.origin}${location.pathname}#${id}`);setCopied(true);setTimeout(()=>setCopied(false),1000)}} aria-label={`Copy link to ${children}`}>{copied?<Check/>:<Hash/>}</Button>{children}</h2>}
export function EndpointContent({ endpoint }: {endpoint:ApiEndpoint}) { const methodStyle:Record<string,string>={GET:"bg-info-ground text-info",POST:"bg-success-ground text-success",PATCH:"bg-warning-ground text-warning",DELETE:"bg-danger-ground text-danger"}; return <><p className="mb-3 text-xs font-extrabold uppercase tracking-[0.18em] text-ink-muted">{endpoint.group}</p><div className="flex flex-wrap items-center gap-3"><span className={cn("rounded-full px-2.5 py-1 font-mono text-xs font-bold",methodStyle[endpoint.method])}>{endpoint.method}</span><h1 className="font-display text-[28px] font-extrabold leading-9">{endpoint.title}</h1></div><code className="mt-5 block overflow-x-auto rounded-md border bg-muted/50 px-4 py-3 font-mono text-sm">{endpoint.path}</code><p className="mt-6 text-lg leading-8 text-muted-foreground">{endpoint.description}</p><div className="mt-10 space-y-9"><section><AnchorHeading id="parameters">Request parameters</AnchorHeading>{endpoint.params.length?<div className="mt-5 overflow-x-auto rounded-md border"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted/60 text-xs text-muted-foreground"><tr><th className="px-4 py-3">Name</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody>{endpoint.params.map(param=><tr key={param.name} className="border-t"><td className="px-4 py-3 font-mono text-xs text-primary">{param.name}</td><td className="font-mono text-xs">{param.type}</td><td><span className={cn("text-xs",param.required?"font-semibold":"text-muted-foreground")}>{param.required?"Required":"Optional"}</span></td><td className="max-w-sm py-3 pr-4 leading-6 text-muted-foreground">{param.description}{param.allowed&&<span className="mt-1 block text-xs">Allowed: <code>{param.allowed}</code></span>}</td></tr>)}</tbody></table></div>:<p className="mt-4 text-content">This endpoint has no request parameters.</p>}</section><section><AnchorHeading id="responses">Responses</AnchorHeading><CodeBlock code={JSON.stringify(endpoint.success,null,2)} label="200 Success"/><CodeBlock code={JSON.stringify(endpoint.error,null,2)} label="Error response"/></section>{endpoint.webhook&&<section><AnchorHeading id="webhook">Related webhook</AnchorHeading><p className="mt-4 text-content">Listen for <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-sm text-primary">{endpoint.webhook}</code> to receive the asynchronous outcome.</p></section>}{endpoint.notes&&<section><AnchorHeading id="notes">Notes</AnchorHeading>{endpoint.notes.map(note=><p className="mt-4 text-content" key={note}>{note}</p>)}</section>}</div></> }
export function EndpointCodeRail({endpoint}:{endpoint:ApiEndpoint}){return <Tabs defaultValue="curl"><TabsList className="grid w-full grid-cols-4"><TabsTrigger value="curl">cURL</TabsTrigger><TabsTrigger value="node">Node</TabsTrigger><TabsTrigger value="python">Python</TabsTrigger><TabsTrigger value="php">PHP</TabsTrigger></TabsList>{["curl","node","python","php"].map(lang=><TabsContent key={lang} value={lang}><CodeBlock code={requestCode(endpoint,lang)} label={`${lang.toUpperCase()} request`}/></TabsContent>)}</Tabs>}
