/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ApiReferenceIndexRouteImport } from './routes/api-reference.index'
import { Route as ApiReferenceSlugRouteImport } from './routes/api-reference.$slug'
import { Route as ApiReferenceSlugDotmdRouteImport } from './routes/api-reference.$slug[.]md'
import { Route as ApiAssistantFeedbackRouteImport } from './routes/api.assistant-feedback'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as GuidesSlugDotmdRouteImport } from './routes/guides.$slug[.]md'
import { Route as GuidesAmountMismatchesRouteImport } from './routes/guides.amount-mismatches'
import { Route as GuidesDedicatedAccountsRouteImport } from './routes/guides.dedicated-accounts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceIndexRoute = ApiReferenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const ApiReferenceSlugRoute = ApiReferenceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const ApiReferenceSlugDotmdRoute = ApiReferenceSlugDotmdRouteImport.update({
  id: '/$slug.md',
  path: '/$slug.md',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const ApiAssistantFeedbackRoute = ApiAssistantFeedbackRouteImport.update({
  id: '/api/assistant-feedback',
  path: '/api/assistant-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugDotmdRoute = GuidesSlugDotmdRouteImport.update({
  id: '/guides/$slug.md',
  path: '/guides/$slug.md',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAmountMismatchesRoute = GuidesAmountMismatchesRouteImport.update({
  id: '/guides/amount-mismatches',
  path: '/guides/amount-mismatches',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDedicatedAccountsRoute = GuidesDedicatedAccountsRouteImport.update({
  id: '/guides/dedicated-accounts',
  path: '/guides/dedicated-accounts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/reference': typeof ReferenceRoute
  '/api-reference/$slug': typeof ApiReferenceSlugRoute
  '/api-reference/$slug.md': typeof ApiReferenceSlugDotmdRoute
  '/api/assistant-feedback': typeof ApiAssistantFeedbackRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/$slug.md': typeof GuidesSlugDotmdRoute
  '/guides/amount-mismatches': typeof GuidesAmountMismatchesRoute
  '/guides/dedicated-accounts': typeof GuidesDedicatedAccountsRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/reference': typeof ReferenceRoute
  '/api-reference/$slug': typeof ApiReferenceSlugRoute
  '/api-reference/$slug.md': typeof ApiReferenceSlugDotmdRoute
  '/api/assistant-feedback': typeof ApiAssistantFeedbackRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/$slug.md': typeof GuidesSlugDotmdRoute
  '/guides/amount-mismatches': typeof GuidesAmountMismatchesRoute
  '/guides/dedicated-accounts': typeof GuidesDedicatedAccountsRoute
  '/api-reference': typeof ApiReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/reference': typeof ReferenceRoute
  '/api-reference/$slug': typeof ApiReferenceSlugRoute
  '/api-reference/$slug.md': typeof ApiReferenceSlugDotmdRoute
  '/api/assistant-feedback': typeof ApiAssistantFeedbackRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/$slug.md': typeof GuidesSlugDotmdRoute
  '/guides/amount-mismatches': typeof GuidesAmountMismatchesRoute
  '/guides/dedicated-accounts': typeof GuidesDedicatedAccountsRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference'
    | '/llms.txt'
    | '/reference'
    | '/api-reference/$slug'
    | '/api-reference/$slug.md'
    | '/api/assistant-feedback'
    | '/api/chat'
    | '/guides/$slug'
    | '/guides/$slug.md'
    | '/guides/amount-mismatches'
    | '/guides/dedicated-accounts'
    | '/api-reference/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/reference'
    | '/api-reference/$slug'
    | '/api-reference/$slug.md'
    | '/api/assistant-feedback'
    | '/api/chat'
    | '/guides/$slug'
    | '/guides/$slug.md'
    | '/guides/amount-mismatches'
    | '/guides/dedicated-accounts'
    | '/api-reference'
  id:
    | '__root__'
    | '/'
    | '/api-reference'
    | '/llms.txt'
    | '/reference'
    | '/api-reference/$slug'
    | '/api-reference/$slug.md'
    | '/api/assistant-feedback'
    | '/api/chat'
    | '/guides/$slug'
    | '/guides/$slug.md'
    | '/guides/amount-mismatches'
    | '/guides/dedicated-accounts'
    | '/api-reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceRoute: typeof ApiReferenceRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ReferenceRoute: typeof ReferenceRoute
  ApiAssistantFeedbackRoute: typeof ApiAssistantFeedbackRoute
  ApiChatRoute: typeof ApiChatRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesSlugDotmdRoute: typeof GuidesSlugDotmdRoute
  GuidesAmountMismatchesRoute: typeof GuidesAmountMismatchesRoute
  GuidesDedicatedAccountsRoute: typeof GuidesDedicatedAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/': {
      id: '/api-reference/'
      path: '/'
      fullPath: '/api-reference/'
      preLoaderRoute: typeof ApiReferenceIndexRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/api-reference/$slug': {
      id: '/api-reference/$slug'
      path: '/$slug'
      fullPath: '/api-reference/$slug'
      preLoaderRoute: typeof ApiReferenceSlugRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/api-reference/$slug.md': {
      id: '/api-reference/$slug.md'
      path: '/$slug.md'
      fullPath: '/api-reference/$slug.md'
      preLoaderRoute: typeof ApiReferenceSlugDotmdRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/api/assistant-feedback': {
      id: '/api/assistant-feedback'
      path: '/api/assistant-feedback'
      fullPath: '/api/assistant-feedback'
      preLoaderRoute: typeof ApiAssistantFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug.md': {
      id: '/guides/$slug.md'
      path: '/guides/$slug.md'
      fullPath: '/guides/$slug.md'
      preLoaderRoute: typeof GuidesSlugDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/amount-mismatches': {
      id: '/guides/amount-mismatches'
      path: '/guides/amount-mismatches'
      fullPath: '/guides/amount-mismatches'
      preLoaderRoute: typeof GuidesAmountMismatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/dedicated-accounts': {
      id: '/guides/dedicated-accounts'
      path: '/guides/dedicated-accounts'
      fullPath: '/guides/dedicated-accounts'
      preLoaderRoute: typeof GuidesDedicatedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiReferenceRouteChildren {
  ApiReferenceSlugRoute: typeof ApiReferenceSlugRoute
  ApiReferenceSlugDotmdRoute: typeof ApiReferenceSlugDotmdRoute
  ApiReferenceIndexRoute: typeof ApiReferenceIndexRoute
}

const ApiReferenceRouteChildren: ApiReferenceRouteChildren = {
  ApiReferenceSlugRoute: ApiReferenceSlugRoute,
  ApiReferenceSlugDotmdRoute: ApiReferenceSlugDotmdRoute,
  ApiReferenceIndexRoute: ApiReferenceIndexRoute,
}

const ApiReferenceRouteWithChildren = ApiReferenceRoute._addFileChildren(
  ApiReferenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceRoute: ApiReferenceRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ReferenceRoute: ReferenceRoute,
  ApiAssistantFeedbackRoute: ApiAssistantFeedbackRoute,
  ApiChatRoute: ApiChatRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesSlugDotmdRoute: GuidesSlugDotmdRoute,
  GuidesAmountMismatchesRoute: GuidesAmountMismatchesRoute,
  GuidesDedicatedAccountsRoute: GuidesDedicatedAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
