/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as ApiReferenceIndexRouteImport } from './routes/api-reference.index'
import { Route as ApiReferenceSlugRouteImport } from './routes/api-reference.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceIndexRoute = ApiReferenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const ApiReferenceSlugRoute = ApiReferenceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiReferenceRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRouteWithChildren
  '/api-reference/$slug': typeof ApiReferenceSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-reference/$slug': typeof ApiReferenceSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/api-reference': typeof ApiReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRouteWithChildren
  '/api-reference/$slug': typeof ApiReferenceSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/api-reference/': typeof ApiReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference'
    | '/api-reference/$slug'
    | '/guides/$slug'
    | '/api-reference/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-reference/$slug' | '/guides/$slug' | '/api-reference'
  id:
    | '__root__'
    | '/'
    | '/api-reference'
    | '/api-reference/$slug'
    | '/guides/$slug'
    | '/api-reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceRoute: typeof ApiReferenceRouteWithChildren
  GuidesSlugRoute: typeof GuidesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference/': {
      id: '/api-reference/'
      path: '/'
      fullPath: '/api-reference/'
      preLoaderRoute: typeof ApiReferenceIndexRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/api-reference/$slug': {
      id: '/api-reference/$slug'
      path: '/$slug'
      fullPath: '/api-reference/$slug'
      preLoaderRoute: typeof ApiReferenceSlugRouteImport
      parentRoute: typeof ApiReferenceRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiReferenceRouteChildren {
  ApiReferenceSlugRoute: typeof ApiReferenceSlugRoute
  ApiReferenceIndexRoute: typeof ApiReferenceIndexRoute
}

const ApiReferenceRouteChildren: ApiReferenceRouteChildren = {
  ApiReferenceSlugRoute: ApiReferenceSlugRoute,
  ApiReferenceIndexRoute: ApiReferenceIndexRoute,
}

const ApiReferenceRouteWithChildren = ApiReferenceRoute._addFileChildren(
  ApiReferenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceRoute: ApiReferenceRouteWithChildren,
  GuidesSlugRoute: GuidesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
